//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arqueo
    {
        public int IdArqueo { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public decimal Ingreso { get; set; }
        public decimal OtroIngreso { get; set; }
        public decimal TotalIngreso { get; set; }
        public decimal TotalEfectivo { get; set; }
        public decimal TotalGasto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int IdArticulo { get; set; }
        public byte IdCategoria { get; set; }
        public int IdUsuario { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Contenido { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int IdAuditoria { get; set; }
        public string Descripcion { get; set; }
        public string CRUD { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int IdCalificacion { get; set; }
        public byte Pregunta { get; set; }
        public bool Puntaje { get; set; }
        public byte IdControlSanitario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual ControlSanitario ControlSanitario { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.Empleado = new HashSet<Empleado>();
        }
    
        public byte IdCargo { get; set; }
        public string NombreCargo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public byte IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaCliente
    {
        public byte IdCategoriaCliente { get; set; }
        public string NombreCategoriaCliente { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciudad()
        {
            this.Empleado = new HashSet<Empleado>();
            this.Empleado1 = new HashSet<Empleado>();
        }
    
        public byte IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado1 { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string NitCi { get; set; }
        public string CorreoElectronico { get; set; }
        public byte[] FotoUbicacion { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlEntrada
    {
        public int IdControlEntrada { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaHoraEntrada { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlSanitario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlSanitario()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public byte IdControlSanitario { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conyugue
    {
        public int IdConyugue { get; set; }
        public int IdEmpleado { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public string TelefonoRespaldo { get; set; }
        public byte NumeroHijos { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despido
    {
        public int IdDespido { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaDespido { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMovimiento
    {
        public int IdDetalleMovimiento { get; set; }
        public int IdMovimiento { get; set; }
        public int IdProducto { get; set; }
        public decimal PrecioUnitario { get; set; }
        public byte Cantidad { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion()
        {
            this.DireccionMovimiento = new HashSet<DireccionMovimiento>();
        }
    
        public int IdDireccion { get; set; }
        public int IdCliente { get; set; }
        public string NombreDireccion { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionMovimiento> DireccionMovimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionMovimiento
    {
        public int IdDireccionMovimiento { get; set; }
        public int IdDireccion { get; set; }
        public int IdMovimiento { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Movimiento Movimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosificacion()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int IdDosificacion { get; set; }
        public string NroAutorizacion { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public string LlaveDosificacion { get; set; }
        public int NroInicialFactura { get; set; }
        public Nullable<int> NroFinalFactura { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Conyugue = new HashSet<Conyugue>();
            this.Despido = new HashSet<Despido>();
            this.Habilidad = new HashSet<Habilidad>();
            this.ReferenciaLaboral = new HashSet<ReferenciaLaboral>();
            this.ReferenciaPersonal = new HashSet<ReferenciaPersonal>();
            this.Saldo = new HashSet<Saldo>();
        }
    
        public int IdEmpleado { get; set; }
        public byte IdCargo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Ci { get; set; }
        public byte IdCiudad { get; set; }
        public byte LugarNacimiento { get; set; }
        public string TelefonoRespaldo { get; set; }
        public string Direccion { get; set; }
        public string EstadoCivil { get; set; }
        public string NombresPadre { get; set; }
        public string PrimerApellidoPadre { get; set; }
        public string SegundoApellidoPadre { get; set; }
        public string OcupacionPadre { get; set; }
        public string NombresMadre { get; set; }
        public string PrimerApellidoMadre { get; set; }
        public string SegundoApellidoMadre { get; set; }
        public string OcupacionMadre { get; set; }
        public string UltimoCurso { get; set; }
        public string ColegioUnidadEducativa { get; set; }
        public System.DateTime FechaInicioTrabajo { get; set; }
        public string Garantia { get; set; }
        public byte[] Fotografia { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conyugue> Conyugue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despido> Despido { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habilidad> Habilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciaLaboral> ReferenciaLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciaPersonal> ReferenciaPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saldo> Saldo { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int IdException { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public string NombreMetodo { get; set; }
        public string Mensaje { get; set; }
        public string ExcepcionMensaje { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existencia
    {
        public int IdExistencia { get; set; }
        public string TipoExistencia { get; set; }
        public int Cantidad { get; set; }
        public int IdProducto { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistenciaMateriaPrima
    {
        public int IdExistenciaMateriaPrima { get; set; }
        public int IdMateriaPrima { get; set; }
        public decimal CantidadActual { get; set; }
        public decimal CantidadCambio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual MateriaPrima MateriaPrima { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int IdGasto { get; set; }
        public byte IdTipoGasto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int IdUsuario { get; set; }
        public int IdAprovador { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual TipoGasto TipoGasto { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidad
    {
        public int IdHabilidad { get; set; }
        public int IdEmpleado { get; set; }
        public string TipoHabilidad { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int IdMaterial { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual MateriaPrima MateriaPrima { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPrima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MateriaPrima()
        {
            this.ExistenciaMateriaPrima = new HashSet<ExistenciaMateriaPrima>();
            this.Material = new HashSet<Material>();
            this.Produccion = new HashSet<Produccion>();
            this.Provision = new HashSet<Provision>();
        }
    
        public int IdMateriaPrima { get; set; }
        public string NombreMateriaPrima { get; set; }
        public string DescripcionMateriaPrima { get; set; }
        public string UnidadMedida { get; set; }
        public int CantidadMinima { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExistenciaMateriaPrima> ExistenciaMateriaPrima { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produccion> Produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provision> Provision { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimiento()
        {
            this.DetalleMovimiento = new HashSet<DetalleMovimiento>();
            this.DireccionMovimiento = new HashSet<DireccionMovimiento>();
            this.Pago = new HashSet<Pago>();
            this.MovimientoCancelado = new HashSet<MovimientoCancelado>();
        }
    
        public int IdMovimiento { get; set; }
        public string Codigo { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public Nullable<int> IdDosificacion { get; set; }
        public Nullable<int> NroMovimiento { get; set; }
        public string CodigoControl { get; set; }
        public string RazonSocial { get; set; }
        public string NitCi { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMovimiento> DetalleMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionMovimiento> DireccionMovimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual Dosificacion Dosificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCancelado> MovimientoCancelado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCancelado
    {
        public int IdMovimientoCancelado { get; set; }
        public int IdMovimiento { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IdPago { get; set; }
        public int IdMovimiento { get; set; }
        public int IdUsuario { get; set; }
        public decimal CantidadPago { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Movimiento Movimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Arqueo = new HashSet<Arqueo>();
            this.ControlEntrada = new HashSet<ControlEntrada>();
            this.Existencia = new HashSet<Existencia>();
        }
    
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arqueo> Arqueo { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlEntrada> ControlEntrada { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Existencia> Existencia { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioSugerido
    {
        public int IdPrecioSugerido { get; set; }
        public int IdProducto { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion
    {
        public int IdProduccion { get; set; }
        public int IdMateriaPrima { get; set; }
        public int IdProducto { get; set; }
        public decimal CantidadProduccion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual MateriaPrima MateriaPrima { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Existencia = new HashSet<Existencia>();
            this.PrecioSugerido = new HashSet<PrecioSugerido>();
            this.Produccion = new HashSet<Produccion>();
            this.DetalleMovimiento = new HashSet<DetalleMovimiento>();
        }
    
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public byte[] FotoProducto { get; set; }
        public string Descripcion { get; set; }
        public string Consumible { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Existencia> Existencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioSugerido> PrecioSugerido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produccion> Produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMovimiento> DetalleMovimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Material = new HashSet<Material>();
            this.Provision = new HashSet<Provision>();
        }
    
        public int IdProveedor { get; set; }
        public string Direccion { get; set; }
        public string TelefonoRespaldo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provision> Provision { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provision
    {
        public int IdProvision { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public int CantidadProvision { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual MateriaPrima MateriaPrima { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoZona
    {
        public int IdPuntoZona { get; set; }
        public byte IdZona { get; set; }
        public decimal LatitudZona { get; set; }
        public decimal LongitudZona { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Zona Zona { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaLaboral
    {
        public int IdReferenciaLaboral { get; set; }
        public int IdEmpleado { get; set; }
        public string NombreEmpresa { get; set; }
        public string NombresJefe { get; set; }
        public string PrimerApellidoJefe { get; set; }
        public string SegundoApellidoJefe { get; set; }
        public byte TiempoTrabajo { get; set; }
        public string FuncionTrabajo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaPersonal
    {
        public int IdReferenciaPersonal { get; set; }
        public int IdEmpleado { get; set; }
        public string NombresFamiliar { get; set; }
        public string PrimerApellidoFamiliar { get; set; }
        public string SegundoApellidoFamiliar { get; set; }
        public string Parentesco { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldo
    {
        public int IdSaldo { get; set; }
        public int IdEmpleado { get; set; }
        public decimal Cantidad { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoGasto()
        {
            this.Gasto = new HashSet<Gasto>();
        }
    
        public byte IdTipoGasto { get; set; }
        public string NombreTipoGasto { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public byte IdTipoUsuario { get; set; }
        public string NombreTipoUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UbicacionDistribuidor
    {
        public int IdUbicacion { get; set; }
        public int IdUsuario { get; set; }
        public string NombreDispositivo { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Articulo = new HashSet<Articulo>();
            this.ControlEntrada = new HashSet<ControlEntrada>();
            this.ControlSanitario = new HashSet<ControlSanitario>();
            this.ExceptionLog = new HashSet<ExceptionLog>();
            this.Existencia = new HashSet<Existencia>();
            this.Gasto = new HashSet<Gasto>();
            this.Gasto1 = new HashSet<Gasto>();
            this.Pago = new HashSet<Pago>();
            this.Arqueo = new HashSet<Arqueo>();
            this.UbicacionDistribuidor = new HashSet<UbicacionDistribuidor>();
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlEntrada> ControlEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSanitario> ControlSanitario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionLog> ExceptionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Existencia> Existencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arqueo> Arqueo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbicacionDistribuidor> UbicacionDistribuidor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zona()
        {
            this.PuntoZona = new HashSet<PuntoZona>();
        }
    
        public byte IdZona { get; set; }
        public string NombreZona { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntoZona> PuntoZona { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Arqueo_O_Fecha_Result
    {
        public int IdArqueo { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public decimal Ingreso { get; set; }
        public decimal OtroIngreso { get; set; }
        public decimal TotalIngreso { get; set; }
        public decimal TotalEfectivo { get; set; }
        public decimal TotalGasto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Arqueo_O_IdArqueo_Result
    {
        public int IdArqueo { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public decimal Ingreso { get; set; }
        public decimal OtroIngreso { get; set; }
        public decimal TotalIngreso { get; set; }
        public decimal TotalEfectivo { get; set; }
        public decimal TotalGasto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Arqueo_O_IdUsuario_Fecha_Result
    {
        public int IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Arqueo_O_Result
    {
        public int IdArqueo { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public decimal Ingreso { get; set; }
        public decimal OtroIngreso { get; set; }
        public decimal TotalIngreso { get; set; }
        public decimal TotalEfectivo { get; set; }
        public decimal TotalGasto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Arqueo_Pago_IdUsuario_Fecha_Result
    {
        public int IdPago { get; set; }
        public string Codigo { get; set; }
        public decimal CantidadPago { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Articulo_O_IdArticulo_Result
    {
        public int IdArticulo { get; set; }
        public byte IdCategoria { get; set; }
        public int IdUsuario { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Contenido { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Articulo_O_Result
    {
        public int IdArticulo { get; set; }
        public byte IdCategoria { get; set; }
        public int IdUsuario { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Contenido { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Calificacion_O_IdCalificacion_Result
    {
        public int IdCalificacion { get; set; }
        public byte Pregunta { get; set; }
        public bool Puntaje { get; set; }
        public byte IdControlSanitario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Calificacion_O_Result
    {
        public int IdCalificacion { get; set; }
        public byte Pregunta { get; set; }
        public bool Puntaje { get; set; }
        public byte IdControlSanitario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Cargo_O_IdCargo_Result
    {
        public byte IdCargo { get; set; }
        public string NombreCargo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Cargo_O_Result
    {
        public byte IdCargo { get; set; }
        public string NombreCargo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Categoria_O_IdCategoria_Result
    {
        public byte IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Categoria_O_Result
    {
        public byte IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_CategoriaCliente_O_IdCategoriaCliente_Result
    {
        public byte IdCategoriaCliente { get; set; }
        public string NombreCategoriaCliente { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_CategoriaCliente_O_Result
    {
        public byte IdCategoriaCliente { get; set; }
        public string NombreCategoriaCliente { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Ciudad_O_IdCiudad_Result
    {
        public byte IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Ciudad_O_Result
    {
        public byte IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ControlEntrada_O_IdControlEntrada_Result
    {
        public int IdControlEntrada { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaHoraEntrada { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ControlEntrada_O_Result
    {
        public int IdControlEntrada { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaHoraEntrada { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ControlSanitario_O_IdControlSanitario_Result
    {
        public byte IdControlSanitario { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ControlSanitario_O_Result
    {
        public byte IdControlSanitario { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ControlSanitario_Reporte_Fecha_Result
    {
        public byte Pregunta { get; set; }
        public bool Puntaje { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Conyugue_O_IdEmpleado_Result
    {
        public int IdConyugue { get; set; }
        public int IdEmpleado { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public string TelefonoRespaldo { get; set; }
        public byte NumeroHijos { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Conyugue_O_Result
    {
        public int IdConyugue { get; set; }
        public int IdEmpleado { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public string TelefonoRespaldo { get; set; }
        public byte NumeroHijos { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Despido_O_IdEmpleado_Result
    {
        public int IdDespido { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaDespido { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Despido_O_Result
    {
        public int IdDespido { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaDespido { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_DetalleMovimiento_O_IdDetalleMovimiento_Result
    {
        public int IdDetalleMovimiento { get; set; }
        public int IdMovimiento { get; set; }
        public int IdProducto { get; set; }
        public decimal PrecioUnitario { get; set; }
        public byte Cantidad { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_DetalleMovimiento_O_Pedido_IdMovimiento_Result
    {
        public int IdDetalleMovimiento { get; set; }
        public int IdMovimiento { get; set; }
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal PrecioUnitario { get; set; }
        public byte Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_DetalleMovimiento_O_Result
    {
        public int IdDetalleMovimiento { get; set; }
        public int IdMovimiento { get; set; }
        public int IdProducto { get; set; }
        public decimal PrecioUnitario { get; set; }
        public byte Cantidad { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_DireccionMovimiento_O_IdMovimiento_Result
    {
        public int IdDireccionMovimiento { get; set; }
        public int IdDireccion { get; set; }
        public int IdMovimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_DireccionMovimiento_O_Result
    {
        public int IdDireccionMovimiento { get; set; }
        public int IdDireccion { get; set; }
        public int IdMovimiento { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Exception_O_IdException_Result
    {
        public int IdException { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public string NombreMetodo { get; set; }
        public string Mensaje { get; set; }
        public string ExcepcionMensaje { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Exception_O_Result
    {
        public int IdException { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public string NombreMetodo { get; set; }
        public string Mensaje { get; set; }
        public string ExcepcionMensaje { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Existencia_O_IdExistencia_Result
    {
        public int IdExistencia { get; set; }
        public string TipoExistencia { get; set; }
        public int Cantidad { get; set; }
        public int IdProducto { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Existencia_O_IdUsuario_Fecha_TipoExistencia_Result
    {
        public Nullable<long> Cont { get; set; }
        public int IdExistencia { get; set; }
        public string TipoExistencia { get; set; }
        public int Cantidad { get; set; }
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public int IdPersona { get; set; }
        public string NombreCompletoPersonaRegistra { get; set; }
        public int IdUsuario { get; set; }
        public string NombreCompletoUsuarioValida { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Existencia_O_Result
    {
        public int IdExistencia { get; set; }
        public string TipoExistencia { get; set; }
        public int Cantidad { get; set; }
        public int IdProducto { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ExistenciaMateriaPrima_O_IdExistenciaMateriaPrima_Result
    {
        public int IdExistenciaMateriaPrima { get; set; }
        public int IdMateriaPrima { get; set; }
        public decimal CantidadActual { get; set; }
        public decimal CantidadCambio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ExistenciaMateriaPrima_O_Result
    {
        public int IdExistenciaMateriaPrima { get; set; }
        public int IdMateriaPrima { get; set; }
        public decimal CantidadActual { get; set; }
        public decimal CantidadCambio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Gasto_O_IdGasto_Result
    {
        public int IdGasto { get; set; }
        public byte IdTipoGasto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int IdUsuario { get; set; }
        public int IdAprovador { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Gasto_O_IdUsuario_Fecha_Result
    {
        public Nullable<long> Cont { get; set; }
        public int IdGasto { get; set; }
        public byte IdTipoGasto { get; set; }
        public string NombreTipoGasto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public int IdAprovador { get; set; }
        public string NombreAprobador { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Gasto_O_Result
    {
        public int IdGasto { get; set; }
        public byte IdTipoGasto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int IdUsuario { get; set; }
        public int IdAprovador { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Habilidad_O_IdEmpleado_Result
    {
        public int IdHabilidad { get; set; }
        public int IdEmpleado { get; set; }
        public string TipoHabilidad { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Habilidad_O_Result
    {
        public int IdHabilidad { get; set; }
        public int IdEmpleado { get; set; }
        public string TipoHabilidad { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Material_O_IdMaterial_Result
    {
        public int IdMaterial { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Material_O_Result
    {
        public int IdMaterial { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_MateriaPrima_O_IdMateriaPrima_Result
    {
        public int IdMateriaPrima { get; set; }
        public string NombreMateriaPrima { get; set; }
        public string DescripcionMateriaPrima { get; set; }
        public string UnidadMedida { get; set; }
        public int CantidadMinima { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_MateriaPrima_O_Result
    {
        public int IdMateriaPrima { get; set; }
        public string NombreMateriaPrima { get; set; }
        public string DescripcionMateriaPrima { get; set; }
        public string UnidadMedida { get; set; }
        public int CantidadMinima { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Movimiento_O_Codigo_Result
    {
        public int IdMovimiento { get; set; }
        public string Codigo { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Movimiento_O_IdMovimiento_Result
    {
        public int IdMovimiento { get; set; }
        public string Codigo { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Movimiento_O_IdUsuario_Fecha_TipoMovimiento_Result
    {
        public Nullable<long> Cont { get; set; }
        public int IdMovimiento { get; set; }
        public string Codigo { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Movimiento_O_Pedido_IdUsuario_Result
    {
        public int IdMovimiento { get; set; }
        public string Codigo { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Telefono { get; set; }
        public int IdDireccion { get; set; }
        public string NombreDireccion { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string RazonSocial { get; set; }
        public string NitCi { get; set; }
        public byte[] FotoUbicacion { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Movimiento_O_Result
    {
        public int IdMovimiento { get; set; }
        public string Codigo { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Pago_O_IdPago_Result
    {
        public int IdPago { get; set; }
        public int IdMovimiento { get; set; }
        public int IdUsuario { get; set; }
        public decimal CantidadPago { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Pago_O_Result
    {
        public int IdPago { get; set; }
        public int IdMovimiento { get; set; }
        public int IdUsuario { get; set; }
        public decimal CantidadPago { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Cliente_O_Buscador_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string RazonSocial { get; set; }
        public string NitCi { get; set; }
        public string CorreoElectronico { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Cliente_O_IdCliente_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string NitCi { get; set; }
        public string CorreoElectronico { get; set; }
        public byte[] FotoUbicacion { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Cliente_O_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string NitCi { get; set; }
        public string CorreoElectronico { get; set; }
        public byte[] FotoUbicacion { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Empleado_O_Buscador_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdEmpleado { get; set; }
        public byte IdCargo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Ci { get; set; }
        public byte IdCiudad { get; set; }
        public byte LugarNacimiento { get; set; }
        public string TelefonoRespaldo { get; set; }
        public string Direccion { get; set; }
        public string EstadoCivil { get; set; }
        public string NombresPadre { get; set; }
        public string PrimerApellidoPadre { get; set; }
        public string SegundoApellidoPadre { get; set; }
        public string OcupacionPadre { get; set; }
        public string NombresMadre { get; set; }
        public string PrimerApellidoMadre { get; set; }
        public string SegundoApellidoMadre { get; set; }
        public string OcupacionMadre { get; set; }
        public string UltimoCurso { get; set; }
        public string ColegioUnidadEducativa { get; set; }
        public System.DateTime FechaInicioTrabajo { get; set; }
        public string Garantia { get; set; }
        public byte[] Fotografia { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Empleado_O_IdEmpleado_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdEmpleado { get; set; }
        public byte IdCargo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Ci { get; set; }
        public byte IdCiudad { get; set; }
        public byte LugarNacimiento { get; set; }
        public string TelefonoRespaldo { get; set; }
        public string Direccion { get; set; }
        public string EstadoCivil { get; set; }
        public string NombresPadre { get; set; }
        public string PrimerApellidoPadre { get; set; }
        public string SegundoApellidoPadre { get; set; }
        public string OcupacionPadre { get; set; }
        public string NombresMadre { get; set; }
        public string PrimerApellidoMadre { get; set; }
        public string SegundoApellidoMadre { get; set; }
        public string OcupacionMadre { get; set; }
        public string UltimoCurso { get; set; }
        public string ColegioUnidadEducativa { get; set; }
        public System.DateTime FechaInicioTrabajo { get; set; }
        public string Garantia { get; set; }
        public byte[] Fotografia { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Empleado_O_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdEmpleado { get; set; }
        public byte IdCargo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Ci { get; set; }
        public byte IdCiudad { get; set; }
        public byte LugarNacimiento { get; set; }
        public string TelefonoRespaldo { get; set; }
        public string Direccion { get; set; }
        public string EstadoCivil { get; set; }
        public string NombresPadre { get; set; }
        public string PrimerApellidoPadre { get; set; }
        public string SegundoApellidoPadre { get; set; }
        public string OcupacionPadre { get; set; }
        public string NombresMadre { get; set; }
        public string PrimerApellidoMadre { get; set; }
        public string SegundoApellidoMadre { get; set; }
        public string OcupacionMadre { get; set; }
        public string UltimoCurso { get; set; }
        public string ColegioUnidadEducativa { get; set; }
        public System.DateTime FechaInicioTrabajo { get; set; }
        public string Garantia { get; set; }
        public byte[] Fotografia { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_O_IdPersona_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_O_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Proveedor_O_IdProveedor_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdProveedor { get; set; }
        public string Direccion { get; set; }
        public string TelefonoRespaldo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Persona_Proveedor_O_Result
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
        public int IdProveedor { get; set; }
        public string Direccion { get; set; }
        public string TelefonoRespaldo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_PrecioSugerido_O_IdPrecioSugerido_Result
    {
        public int IdPrecioSugerido { get; set; }
        public int IdProducto { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_PrecioSugerido_O_Result
    {
        public int IdPrecioSugerido { get; set; }
        public int IdProducto { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Produccion_O_IdProduccion_Result
    {
        public int IdProduccion { get; set; }
        public int IdMateriaPrima { get; set; }
        public int IdProducto { get; set; }
        public decimal CantidadProduccion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Produccion_O_Result
    {
        public int IdProduccion { get; set; }
        public int IdMateriaPrima { get; set; }
        public int IdProducto { get; set; }
        public decimal CantidadProduccion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Producto_O_IdProducto_Result
    {
        public int idProducto { get; set; }
        public string NombreProducto { get; set; }
        public byte[] FotoProducto { get; set; }
        public string Descripcion { get; set; }
        public string Consumible { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Producto_O_Mobil_Result
    {
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Producto_O_Result
    {
        public int idProducto { get; set; }
        public string NombreProducto { get; set; }
        public byte[] FotoProducto { get; set; }
        public string Descripcion { get; set; }
        public string Consumible { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Provision_O_IdProvision_Result
    {
        public int IdProvision { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public int CantidadProvision { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Provision_O_Result
    {
        public int IdProvision { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public int CantidadProvision { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_PuntoZona_O_IdPuntoZona_Result
    {
        public int IdPuntoZona { get; set; }
        public byte IdZona { get; set; }
        public decimal LatitudZona { get; set; }
        public decimal LongitudZona { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_PuntoZona_O_Result
    {
        public int IdPuntoZona { get; set; }
        public byte IdZona { get; set; }
        public decimal LatitudZona { get; set; }
        public decimal LongitudZona { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ReferenciaLaboral_O_IdEmpleado_Result
    {
        public int IdReferenciaLaboral { get; set; }
        public int IdEmpleado { get; set; }
        public string NombreEmpresa { get; set; }
        public string NombresJefe { get; set; }
        public string PrimerApellidoJefe { get; set; }
        public string SegundoApellidoJefe { get; set; }
        public byte TiempoTrabajo { get; set; }
        public string FuncionTrabajo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ReferenciaLaboral_O_Result
    {
        public int IdReferenciaLaboral { get; set; }
        public int IdEmpleado { get; set; }
        public string NombreEmpresa { get; set; }
        public string NombresJefe { get; set; }
        public string PrimerApellidoJefe { get; set; }
        public string SegundoApellidoJefe { get; set; }
        public byte TiempoTrabajo { get; set; }
        public string FuncionTrabajo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ReferenciaPersonal_O_IdEmpleado_Result
    {
        public int IdReferenciaPersonal { get; set; }
        public int IdEmpleado { get; set; }
        public string NombresFamiliar { get; set; }
        public string PrimerApellidoFamiliar { get; set; }
        public string SegundoApellidoFamiliar { get; set; }
        public string Parentesco { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_ReferenciaPersonal_O_Result
    {
        public int IdReferenciaPersonal { get; set; }
        public int IdEmpleado { get; set; }
        public string NombresFamiliar { get; set; }
        public string PrimerApellidoFamiliar { get; set; }
        public string SegundoApellidoFamiliar { get; set; }
        public string Parentesco { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Rep_Cliente_Zona_Result
    {
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string CorreoElectronico { get; set; }
        public string NombreCategoriaCliente { get; set; }
        public string Mapa { get; set; }
        public string NombreZona { get; set; }
        public string Contrato { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Asistencia_Result
    {
        public string NombreCompleto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string HoraEntrada { get; set; }
        public string HoraSalida { get; set; }
        public string Modificado { get; set; }
        public int num { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Cliente_Categoria_Result
    {
        public string NombreCategoriaCliente { get; set; }
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Contrato { get; set; }
        public int num { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Deuda_Result
    {
        public int IdMovimiento { get; set; }
        public string NombrePersonal { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Existencia_Nuevo_Result
    {
        public string Producto { get; set; }
        public string Movimiento { get; set; }
        public int Cantidad { get; set; }
        public string NombrePersonal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Existencia_Result
    {
        public string Producto { get; set; }
        public string Movimiento { get; set; }
        public int Cantidad { get; set; }
        public string NombrePersonal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Movimiento_Result
    {
        public string Codigo { get; set; }
        public string Cliente { get; set; }
        public string Personal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Reporte_Saldo_Result
    {
        public string NombrePersonal { get; set; }
        public decimal Cantidad { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Saldo_O_IdSaldo_Result
    {
        public int IdSaldo { get; set; }
        public int IdEmpleado { get; set; }
        public decimal Cantidad { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Saldo_O_Result
    {
        public int IdSaldo { get; set; }
        public int IdEmpleado { get; set; }
        public decimal Cantidad { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_TipoGasto_O_IdTipoGasto_Result
    {
        public byte IdTipoGasto { get; set; }
        public string NombreTipoGasto { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_TipoGasto_O_Result
    {
        public byte IdTipoGasto { get; set; }
        public string NombreTipoGasto { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_UbicacionDistribuidor_O_IdUsuario_Result
    {
        public int IdUbicacion { get; set; }
        public int IdUsuario { get; set; }
        public string NombreCompleto { get; set; }
        public string NombreDispositivo { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Usuario_O_IdUsuario_Result
    {
        public int IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Usuario_O_Result
    {
        public int IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Zona_O_IdZona_Result
    {
        public byte IdZona { get; set; }
        public string NombreZona { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
namespace Modelo
{
    using System;
    
    public partial class Proc_Zona_O_Result
    {
        public byte IdZona { get; set; }
        public string NombreZona { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Estado { get; set; }
    }
}
